# Site settings
title: "Bookletix faq"
email: faq@bookletix.com
description: ""
baseurl: ""
url: ""
twitter_username: "bookletix"
github_username:  "bookletix"
color_theme:  "#fff"
color_text:  "rgb(173, 172, 173)"
language:  "en"

# Build settings
markdown: kramdown
permalink: /:title/
gems: [jekyll-paginate]
paginate: 5

# Plugins
plugins_dir:
  - jekyll-admin

theme: jekyll-theme-cayman
